insert into posts (user_id, caption) values (27, 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus');
insert into posts (user_id, caption) values (18, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros');
insert into posts (user_id, caption) values (16, 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse');
insert into posts (user_id, caption) values (17, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in');
insert into posts (user_id, caption) values (23, 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into posts (user_id, caption) values (18, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into posts (user_id, caption) values (18, 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero');
insert into posts (user_id, caption) values (20, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into posts (user_id, caption) values (28, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into posts (user_id, caption) values (24, 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into posts (user_id, caption) values (28, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est');
insert into posts (user_id, caption) values (26, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
insert into posts (user_id, caption) values (27, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci');
insert into posts (user_id, caption) values (22, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into posts (user_id, caption) values (27, 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into posts (user_id, caption) values (23, 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into posts (user_id, caption) values (19, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst');
insert into posts (user_id, caption) values (23, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis');
insert into posts (user_id, caption) values (20, 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into posts (user_id, caption) values (26, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit');
insert into posts (user_id, caption) values (22, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into posts (user_id, caption) values (20, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo');
insert into posts (user_id, caption) values (16, 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into posts (user_id, caption) values (25, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into posts (user_id, caption) values (17, 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis');
insert into posts (user_id, caption) values (24, 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into posts (user_id, caption) values (27, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into posts (user_id, caption) values (22, 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin');
insert into posts (user_id, caption) values (17, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into posts (user_id, caption) values (24, 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero');
insert into posts (user_id, caption) values (23, 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet');
insert into posts (user_id, caption) values (24, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into posts (user_id, caption) values (16, 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into posts (user_id, caption) values (23, 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est');
insert into posts (user_id, caption) values (20, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in');
insert into posts (user_id, caption) values (25, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into posts (user_id, caption) values (24, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi');
insert into posts (user_id, caption) values (16, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio');
insert into posts (user_id, caption) values (19, 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed');
insert into posts (user_id, caption) values (21, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into posts (user_id, caption) values (22, 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac');
insert into posts (user_id, caption) values (28, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi');
insert into posts (user_id, caption) values (18, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan');
insert into posts (user_id, caption) values (20, 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into posts (user_id, caption) values (23, 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis');
insert into posts (user_id, caption) values (26, 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into posts (user_id, caption) values (26, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae');
insert into posts (user_id, caption) values (24, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis');
insert into posts (user_id, caption) values (24, 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel');
insert into posts (user_id, caption) values (18, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into posts (user_id, caption) values (17, 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc');
insert into posts (user_id, caption) values (23, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into posts (user_id, caption) values (27, 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum');
insert into posts (user_id, caption) values (24, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into posts (user_id, caption) values (26, 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into posts (user_id, caption) values (23, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque');
insert into posts (user_id, caption) values (19, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at');
insert into posts (user_id, caption) values (21, 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui');
insert into posts (user_id, caption) values (17, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into posts (user_id, caption) values (17, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris');
insert into posts (user_id, caption) values (20, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi');
insert into posts (user_id, caption) values (20, 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into posts (user_id, caption) values (16, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi');
insert into posts (user_id, caption) values (16, 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris');
insert into posts (user_id, caption) values (22, 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo');
insert into posts (user_id, caption) values (21, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac');
insert into posts (user_id, caption) values (26, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut');
insert into posts (user_id, caption) values (24, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into posts (user_id, caption) values (17, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into posts (user_id, caption) values (19, 'mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse');
insert into posts (user_id, caption) values (22, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat');
insert into posts (user_id, caption) values (18, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin');
insert into posts (user_id, caption) values (25, 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum');
insert into posts (user_id, caption) values (19, 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien');
insert into posts (user_id, caption) values (18, 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis');
insert into posts (user_id, caption) values (20, 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum');
insert into posts (user_id, caption) values (24, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut');
insert into posts (user_id, caption) values (24, 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into posts (user_id, caption) values (25, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum');
insert into posts (user_id, caption) values (25, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit');
insert into posts (user_id, caption) values (18, 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor');
insert into posts (user_id, caption) values (27, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into posts (user_id, caption) values (20, 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero');
insert into posts (user_id, caption) values (21, 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into posts (user_id, caption) values (20, 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut');
insert into posts (user_id, caption) values (25, 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit');
insert into posts (user_id, caption) values (17, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit');
insert into posts (user_id, caption) values (23, 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus');
insert into posts (user_id, caption) values (20, 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a');
insert into posts (user_id, caption) values (22, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus');
insert into posts (user_id, caption) values (23, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
insert into posts (user_id, caption) values (25, 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into posts (user_id, caption) values (19, 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue');
insert into posts (user_id, caption) values (19, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into posts (user_id, caption) values (21, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into posts (user_id, caption) values (19, 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into posts (user_id, caption) values (22, 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into posts (user_id, caption) values (21, 'mattis nibh ligula nec sem duis aliquam convallis nunc proin');
insert into posts (user_id, caption) values (27, 'dapibus duis at velit eu est congue elementum in hac');
insert into posts (user_id, caption) values (21, 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra');

insert into posts_reactions (post_id, liked_id, comment) values (1, 25, 'luctus nec molestie sed');
insert into posts_reactions (post_id, liked_id, comment) values (6, 24, 'sed tincidunt eu felis fusce');
insert into posts_reactions (post_id, liked_id, comment) values (9, 26, 'ultrices enim lorem');
insert into posts_reactions (post_id, liked_id, comment) values (4, 28, 'rhoncus aliquam lacus morbi');
insert into posts_reactions (post_id, liked_id, comment) values (14, 23, 'vestibulum ante ipsum primis');
insert into posts_reactions (post_id, liked_id, comment) values (7, 19, 'lacus morbi quis tortor');
insert into posts_reactions (post_id, liked_id, comment) values (6, 25, 'maecenas leo odio condimentum id');
insert into posts_reactions (post_id, liked_id, comment) values (9, 25, 'aenean auctor gravida');
insert into posts_reactions (post_id, liked_id, comment) values (5, 20, 'nascetur ridiculus mus');
insert into posts_reactions (post_id, liked_id, comment) values (11, 21, 'sed tincidunt eu felis fusce');
insert into posts_reactions (post_id, liked_id, comment) values (2, 22, 'sapien urna pretium');
insert into posts_reactions (post_id, liked_id, comment) values (7, 26, 'bibendum imperdiet nullam');
insert into posts_reactions (post_id, liked_id, comment) values (4, 23, 'vitae quam suspendisse potenti nullam');
insert into posts_reactions (post_id, liked_id, comment) values (14, 23, 'mi nulla ac enim in');
insert into posts_reactions (post_id, liked_id, comment) values (13, 27, 'augue vestibulum rutrum rutrum neque');
insert into posts_reactions (post_id, liked_id, comment) values (4, 20, 'pulvinar sed nisl nunc');
insert into posts_reactions (post_id, liked_id, comment) values (2, 26, 'in libero ut');
insert into posts_reactions (post_id, liked_id, comment) values (7, 21, 'lectus suspendisse potenti in eleifend');
insert into posts_reactions (post_id, liked_id, comment) values (5, 20, 'at velit vivamus vel nulla');
insert into posts_reactions (post_id, liked_id, comment) values (8, 19, 'elementum pellentesque quisque porta');
insert into posts_reactions (post_id, liked_id, comment) values (9, 18, 'sit amet lobortis sapien sapien');
insert into posts_reactions (post_id, liked_id, comment) values (14, 20, 'velit eu est congue');
insert into posts_reactions (post_id, liked_id, comment) values (11, 18, 'est quam pharetra');
insert into posts_reactions (post_id, liked_id, comment) values (4, 28, 'sit amet eleifend pede');
insert into posts_reactions (post_id, liked_id, comment) values (5, 22, 'luctus rutrum nulla tellus');
insert into posts_reactions (post_id, liked_id, comment) values (2, 24, 'quam pharetra magna');
insert into posts_reactions (post_id, liked_id, comment) values (5, 28, 'morbi vel lectus in quam');
insert into posts_reactions (post_id, liked_id, comment) values (9, 23, 'ut mauris eget massa tempor');
insert into posts_reactions (post_id, liked_id, comment) values (14, 20, 'donec dapibus duis at');
insert into posts_reactions (post_id, liked_id, comment) values (3, 20, 'mauris eget massa');
insert into posts_reactions (post_id, liked_id, comment) values (6, 17, 'semper est quam pharetra magna');
insert into posts_reactions (post_id, liked_id, comment) values (8, 23, 'massa donec dapibus duis at');
insert into posts_reactions (post_id, liked_id, comment) values (4, 27, 'sodales scelerisque mauris sit amet');
insert into posts_reactions (post_id, liked_id, comment) values (6, 22, 'lacus at velit vivamus vel');
insert into posts_reactions (post_id, liked_id, comment) values (9, 16, 'vel dapibus at diam');
insert into posts_reactions (post_id, liked_id, comment) values (7, 17, 'magnis dis parturient montes');
insert into posts_reactions (post_id, liked_id, comment) values (9, 18, 'posuere felis sed lacus morbi');
insert into posts_reactions (post_id, liked_id, comment) values (8, 18, 'congue eget semper rutrum nulla');
insert into posts_reactions (post_id, liked_id, comment) values (13, 22, 'sit amet sapien dignissim');
insert into posts_reactions (post_id, liked_id, comment) values (9, 19, 'consequat varius integer ac leo');
insert into posts_reactions (post_id, liked_id, comment) values (10, 23, 'et ultrices posuere cubilia');
insert into posts_reactions (post_id, liked_id, comment) values (10, 25, 'odio in hac');
insert into posts_reactions (post_id, liked_id, comment) values (4, 27, 'platea dictumst aliquam');
insert into posts_reactions (post_id, liked_id, comment) values (7, 28, 'neque sapien placerat ante');
insert into posts_reactions (post_id, liked_id, comment) values (10, 26, 'cubilia curae donec');
insert into posts_reactions (post_id, liked_id, comment) values (7, 20, 'sit amet erat nulla');
insert into posts_reactions (post_id, liked_id, comment) values (3, 24, 'at velit eu est congue');
insert into posts_reactions (post_id, liked_id, comment) values (10, 26, 'id mauris vulputate elementum');
insert into posts_reactions (post_id, liked_id, comment) values (10, 21, 'phasellus in felis donec');
insert into posts_reactions (post_id, liked_id, comment) values (7, 26, 'nibh in lectus pellentesque');
insert into posts_reactions (post_id, liked_id, comment) values (14, 25, 'libero non mattis');
insert into posts_reactions (post_id, liked_id, comment) values (13, 27, 'vivamus metus arcu');
insert into posts_reactions (post_id, liked_id, comment) values (11, 16, 'eu mi nulla');
insert into posts_reactions (post_id, liked_id, comment) values (3, 18, 'pretium iaculis diam erat');
insert into posts_reactions (post_id, liked_id, comment) values (4, 24, 'proin interdum mauris non');
insert into posts_reactions (post_id, liked_id, comment) values (7, 27, 'pellentesque eget nunc donec');
insert into posts_reactions (post_id, liked_id, comment) values (3, 24, 'justo nec condimentum neque');
insert into posts_reactions (post_id, liked_id, comment) values (13, 25, 'est lacinia nisi venenatis tristique');
insert into posts_reactions (post_id, liked_id, comment) values (10, 19, 'quam sapien varius');
insert into posts_reactions (post_id, liked_id, comment) values (6, 16, 'consectetuer adipiscing elit proin risus');
insert into posts_reactions (post_id, liked_id, comment) values (4, 17, 'nibh in hac');
insert into posts_reactions (post_id, liked_id, comment) values (6, 20, 'erat nulla tempus vivamus');
insert into posts_reactions (post_id, liked_id, comment) values (4, 18, 'etiam faucibus cursus urna ut');
insert into posts_reactions (post_id, liked_id, comment) values (12, 26, 'sed vestibulum sit amet cursus');
insert into posts_reactions (post_id, liked_id, comment) values (7, 22, 'rhoncus aliquet pulvinar sed nisl');
insert into posts_reactions (post_id, liked_id, comment) values (15, 22, 'id pretium iaculis diam');
insert into posts_reactions (post_id, liked_id, comment) values (7, 21, 'nulla tellus in');
insert into posts_reactions (post_id, liked_id, comment) values (15, 18, 'tellus in sagittis');
insert into posts_reactions (post_id, liked_id, comment) values (4, 22, 'eros vestibulum ac est');
insert into posts_reactions (post_id, liked_id, comment) values (8, 25, 'amet eleifend pede libero quis');
insert into posts_reactions (post_id, liked_id, comment) values (1, 26, 'posuere nonummy integer non');
insert into posts_reactions (post_id, liked_id, comment) values (9, 27, 'ante ipsum primis in faucibus');
insert into posts_reactions (post_id, liked_id, comment) values (2, 17, 'nulla facilisi cras non');
insert into posts_reactions (post_id, liked_id, comment) values (15, 28, 'amet turpis elementum');
insert into posts_reactions (post_id, liked_id, comment) values (15, 21, 'laoreet ut rhoncus aliquet pulvinar');
insert into posts_reactions (post_id, liked_id, comment) values (14, 25, 'dolor morbi vel lectus in');
insert into posts_reactions (post_id, liked_id, comment) values (15, 20, 'purus aliquet at feugiat non');
insert into posts_reactions (post_id, liked_id, comment) values (9, 16, 'sem sed sagittis nam congue');
insert into posts_reactions (post_id, liked_id, comment) values (12, 21, 'nibh in quis');
insert into posts_reactions (post_id, liked_id, comment) values (9, 24, 'convallis eget eleifend');
insert into posts_reactions (post_id, liked_id, comment) values (10, 16, 'aliquam augue quam sollicitudin');
insert into posts_reactions (post_id, liked_id, comment) values (11, 21, 'ut dolor morbi vel');
insert into posts_reactions (post_id, liked_id, comment) values (1, 21, 'ullamcorper purus sit');
insert into posts_reactions (post_id, liked_id, comment) values (5, 22, 'nulla eget eros elementum');
insert into posts_reactions (post_id, liked_id, comment) values (7, 24, 'congue vivamus metus');
insert into posts_reactions (post_id, liked_id, comment) values (9, 28, 'pede ac diam cras');
insert into posts_reactions (post_id, liked_id, comment) values (7, 16, 'nisl ut volutpat');
insert into posts_reactions (post_id, liked_id, comment) values (15, 21, 'posuere felis sed lacus');
insert into posts_reactions (post_id, liked_id, comment) values (1, 17, 'lobortis vel dapibus at diam');
insert into posts_reactions (post_id, liked_id, comment) values (9, 27, 'maecenas rhoncus aliquam lacus');
insert into posts_reactions (post_id, liked_id, comment) values (4, 16, 'congue diam id');
insert into posts_reactions (post_id, liked_id, comment) values (2, 27, 'id luctus nec molestie');
insert into posts_reactions (post_id, liked_id, comment) values (2, 22, 'lectus pellentesque at');
insert into posts_reactions (post_id, liked_id, comment) values (11, 24, 'vestibulum proin eu mi');
insert into posts_reactions (post_id, liked_id, comment) values (1, 18, 'risus semper porta volutpat');
insert into posts_reactions (post_id, liked_id, comment) values (11, 27, 'diam id ornare imperdiet sapien');
insert into posts_reactions (post_id, liked_id, comment) values (11, 16, 'bibendum morbi non quam');
insert into posts_reactions (post_id, liked_id, comment) values (13, 16, 'id sapien in sapien iaculis');
insert into posts_reactions (post_id, liked_id, comment) values (2, 16, 'orci luctus et');
insert into posts_reactions (post_id, liked_id, comment) values (1, 21, 'in hac habitasse platea');


insert into follows (follower_id, followed_id) values (25, 19);
insert into follows (follower_id, followed_id) values (21, 28);
insert into follows (follower_id, followed_id) values (20, 25);
insert into follows (follower_id, followed_id) values (19, 23);
insert into follows (follower_id, followed_id) values (18, 27);
insert into follows (follower_id, followed_id) values (20, 19);
insert into follows (follower_id, followed_id) values (26, 20);
insert into follows (follower_id, followed_id) values (21, 20);
insert into follows (follower_id, followed_id) values (22, 25);
insert into follows (follower_id, followed_id) values (25, 23);
insert into follows (follower_id, followed_id) values (23, 18);
insert into follows (follower_id, followed_id) values (27, 23);
insert into follows (follower_id, followed_id) values (19, 24);
insert into follows (follower_id, followed_id) values (20, 21);
insert into follows (follower_id, followed_id) values (25, 28);
insert into follows (follower_id, followed_id) values (25, 19);
insert into follows (follower_id, followed_id) values (21, 18);
insert into follows (follower_id, followed_id) values (25, 20);
insert into follows (follower_id, followed_id) values (22, 21);
insert into follows (follower_id, followed_id) values (24, 25);
insert into follows (follower_id, followed_id) values (19, 28);
insert into follows (follower_id, followed_id) values (25, 28);
insert into follows (follower_id, followed_id) values (19, 20);
insert into follows (follower_id, followed_id) values (19, 24);
insert into follows (follower_id, followed_id) values (22, 21);
insert into follows (follower_id, followed_id) values (22, 19);
insert into follows (follower_id, followed_id) values (20, 18);
insert into follows (follower_id, followed_id) values (21, 22);
insert into follows (follower_id, followed_id) values (19, 23);
insert into follows (follower_id, followed_id) values (25, 23);
insert into follows (follower_id, followed_id) values (26, 23);
insert into follows (follower_id, followed_id) values (20, 25);
insert into follows (follower_id, followed_id) values (21, 19);
insert into follows (follower_id, followed_id) values (20, 25);
insert into follows (follower_id, followed_id) values (28, 18);
insert into follows (follower_id, followed_id) values (18, 21);
insert into follows (follower_id, followed_id) values (27, 26);
insert into follows (follower_id, followed_id) values (25, 26);
insert into follows (follower_id, followed_id) values (20, 25);
insert into follows (follower_id, followed_id) values (19, 25);
insert into follows (follower_id, followed_id) values (24, 23);
insert into follows (follower_id, followed_id) values (28, 27);
insert into follows (follower_id, followed_id) values (22, 28);
insert into follows (follower_id, followed_id) values (18, 19);
insert into follows (follower_id, followed_id) values (23, 26);
insert into follows (follower_id, followed_id) values (19, 21);
insert into follows (follower_id, followed_id) values (19, 26);
insert into follows (follower_id, followed_id) values (28, 18);
insert into follows (follower_id, followed_id) values (20, 18);
insert into follows (follower_id, followed_id) values (26, 22);
insert into follows (follower_id, followed_id) values (20, 18);
insert into follows (follower_id, followed_id) values (19, 26);
insert into follows (follower_id, followed_id) values (28, 18);
insert into follows (follower_id, followed_id) values (19, 21);
insert into follows (follower_id, followed_id) values (24, 23);
insert into follows (follower_id, followed_id) values (19, 21);
insert into follows (follower_id, followed_id) values (23, 22);
insert into follows (follower_id, followed_id) values (20, 24);
insert into follows (follower_id, followed_id) values (20, 23);
insert into follows (follower_id, followed_id) values (18, 23);
insert into follows (follower_id, followed_id) values (22, 24);
insert into follows (follower_id, followed_id) values (19, 19);
insert into follows (follower_id, followed_id) values (18, 21);
insert into follows (follower_id, followed_id) values (22, 19);
insert into follows (follower_id, followed_id) values (19, 25);
insert into follows (follower_id, followed_id) values (23, 26);
insert into follows (follower_id, followed_id) values (24, 20);
insert into follows (follower_id, followed_id) values (18, 22);
insert into follows (follower_id, followed_id) values (26, 22);
insert into follows (follower_id, followed_id) values (26, 28);
insert into follows (follower_id, followed_id) values (25, 20);
insert into follows (follower_id, followed_id) values (22, 28);
insert into follows (follower_id, followed_id) values (20, 28);
insert into follows (follower_id, followed_id) values (21, 23);
insert into follows (follower_id, followed_id) values (28, 19);
insert into follows (follower_id, followed_id) values (23, 20);
insert into follows (follower_id, followed_id) values (18, 23);
insert into follows (follower_id, followed_id) values (21, 26);
insert into follows (follower_id, followed_id) values (19, 27);
insert into follows (follower_id, followed_id) values (20, 27);
insert into follows (follower_id, followed_id) values (21, 18);
insert into follows (follower_id, followed_id) values (28, 19);
insert into follows (follower_id, followed_id) values (23, 22);
insert into follows (follower_id, followed_id) values (23, 28);
insert into follows (follower_id, followed_id) values (24, 19);
insert into follows (follower_id, followed_id) values (28, 24);
insert into follows (follower_id, followed_id) values (19, 20);
insert into follows (follower_id, followed_id) values (18, 25);
insert into follows (follower_id, followed_id) values (24, 26);
insert into follows (follower_id, followed_id) values (25, 26);
insert into follows (follower_id, followed_id) values (27, 27);
insert into follows (follower_id, followed_id) values (20, 19);
insert into follows (follower_id, followed_id) values (22, 18);
insert into follows (follower_id, followed_id) values (25, 19);
insert into follows (follower_id, followed_id) values (20, 25);
insert into follows (follower_id, followed_id) values (20, 19);
insert into follows (follower_id, followed_id) values (28, 27);
insert into follows (follower_id, followed_id) values (22, 25);
insert into follows (follower_id, followed_id) values (23, 22);